// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CombineExcelFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetExcelFilesSheetNames(arg1:string,arg2:string):Promise<main.SheetResponse>;

export function Greet(arg1:string):Promise<string>;

export function OpenExcelFile():Promise<string>;
