// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CombineExcelFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CombineExcelFiles'](arg1, arg2, arg3, arg4);
}

export function GetExcelFilesSheetNames(arg1, arg2) {
  return window['go']['main']['App']['GetExcelFilesSheetNames'](arg1, arg2);
}

export function GetFileSheetsNames(arg1) {
  return window['go']['main']['App']['GetFileSheetsNames'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenExcelFile() {
  return window['go']['main']['App']['OpenExcelFile']();
}
